import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const courier = Geist({
  variable: "--font-courier",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Flaticon Uicons - Bold Rounded (for the fi-br prefix) */}
        <link 
          rel='stylesheet' 
          href='https://cdn-uicons.flaticon.com/2.1.0/uicons-bold-rounded/css/uicons-bold-rounded.css' 
        />
      </head>
      <body
      suppressHydrationWarning={true}  
        className={`${geistSans.variable} ${geistMono.variable} ${courier.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
